title: Fall Guys @ Sangu
meta-keywords: fallguys fall guys tips tricks shortcuts short movies crown level rewards
description: >
  Short movies with all the Fall Guys shortcuts.
  Overview of the crown level rewards.
baseurl: "/fallguys"
url: "https://sangu.be"


# Social
google_analytics: UA-30075487-3
email: woutervs@hotmail.com


# Blog
github_data_url: https://github.com/SanguPackage/fallguys/tree/master/_posts
collections:
  posts:
    output: true
    permalink: /blog/:categories/:title/
  pages:
    output: true
    permalink: /:title
  levels:
    output: true
    permalink: /levels/:name

# Build settings
markdown: kramdown

# https://github.com/jekyll/minima
# bundle show minima
theme: minima

# https://pages.github.com/versions/
plugins:
  - jemoji # https://github.com/jekyll/jemoji
  - jekyll-gist # https://github.com/jekyll/jekyll-gist
  - jekyll-avatar # https://github.com/benbalter/jekyll-avatar
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
